# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cookiejar.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cookiejar.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0f\x63ookiejar.proto\"6\n\x14\x43ookiejarTransaction\x12\x0e\n\x06\x61\x63tion\x18\x01 \x01(\t\x12\x0e\n\x06\x61mount\x18\x02 \x01(\rb\x06proto3')
)




_COOKIEJARTRANSACTION = _descriptor.Descriptor(
  name='CookiejarTransaction',
  full_name='CookiejarTransaction',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='action', full_name='CookiejarTransaction.action', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='amount', full_name='CookiejarTransaction.amount', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=73,
)

DESCRIPTOR.message_types_by_name['CookiejarTransaction'] = _COOKIEJARTRANSACTION
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CookiejarTransaction = _reflection.GeneratedProtocolMessageType('CookiejarTransaction', (_message.Message,), dict(
  DESCRIPTOR = _COOKIEJARTRANSACTION,
  __module__ = 'cookiejar_pb2'
  # @@protoc_insertion_point(class_scope:CookiejarTransaction)
  ))
_sym_db.RegisterMessage(CookiejarTransaction)


# @@protoc_insertion_point(module_scope)
